// <auto-generated />
namespace DataModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PayslipUserIDDifferentThanID_AppUser_mdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PayslipUserIDDifferentThanID_AppUser_mdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201803250216133_PayslipUserIDDifferentThanID_AppUser_mdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
